# Generated by Django 4.2.6 on 2023-12-10 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTSE_Name', models.CharField(max_length=255)),
                ('TTSE_Symbol', models.CharField(max_length=255)),
                ('TTSE_Sector', models.CharField(blank=True, max_length=255, null=True)),
                ('TTSE_Website', models.CharField(blank=True, max_length=255, null=True)),
                ('TTSE_IssuedShareCap', models.IntegerField(default=0)),
                ('TTSE_MarketCap', models.FloatField(default=0.0)),
                ('Type', models.CharField(blank=True, max_length=500, null=True)),
                ('Note', models.CharField(blank=True, max_length=500, null=True)),
                ('Date_Started', models.DateTimeField(default=django.utils.timezone.now)),
                ('Site', models.CharField(blank=True, max_length=500, null=True)),
                ('total_stocks_purchased', models.IntegerField(default=0)),
                ('total_stocks_sold', models.IntegerField(default=0)),
                ('No_days_since_start', models.IntegerField(default=0, editable=False)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Webscraping_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie_code', models.CharField(blank=True, max_length=500, null=True)),
                ('time_remaining', models.IntegerField(default=28800)),
                ('status', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('number_of_stocks', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.stock_information')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Stock_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPEN', models.FloatField()),
                ('CLOSE', models.FloatField()),
                ('VOLUME_TRADED', models.FloatField()),
                ('stock_date', models.DateTimeField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('stock_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='api.stock_information')),
            ],
            options={
                'ordering': ['stock_date'],
            },
        ),
    ]
