# Generated by Django 4.2.6 on 2023-12-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_information',
            name='total_stocks_purchased',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_information',
            name='total_stocks_sold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='number_of_stocks',
            field=models.FloatField(default=0),
        ),
    ]
