# Generated by Django 4.2.6 on 2023-12-09 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_search_results_pages_alter_search_results_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTSE_Name', models.CharField(max_length=255)),
                ('TTSE_Symbol', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=500)),
                ('Note', models.CharField(max_length=500)),
                ('Date_Started', models.DateTimeField(default=django.utils.timezone.now)),
                ('Site', models.CharField(max_length=500)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Webscraping_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie_code', models.CharField(blank=True, max_length=500, null=True)),
                ('time_remaining', models.IntegerField(default=28800)),
                ('status', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='search_results',
            name='searchquery',
        ),
        migrations.DeleteModel(
            name='Search_Query',
        ),
        migrations.DeleteModel(
            name='Search_Results',
        ),
    ]
