# Generated by Django 4.2.6 on 2023-12-10 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stock_information_webscraping_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_information',
            name='TTSE_IssuedShareCap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock_information',
            name='TTSE_MarketCap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock_information',
            name='TTSE_Sector',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_information',
            name='TTSE_Website',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stock_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPEN', models.FloatField()),
                ('CLOSE', models.FloatField()),
                ('VOLUME_TRADED', models.FloatField()),
                ('stock_date', models.DateTimeField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('stock_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock_information')),
            ],
            options={
                'ordering': ['stock_date'],
            },
        ),
    ]
