# Generated by Django 4.2.6 on 2023-12-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stock_information_no_days_since_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_data',
            name='stock_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='api.stock_information'),
        ),
    ]
